### ISSUE TITLE
 719: error: (-49:Unknown error code -49) 'cv::FileStorage::Impl::open'

### ISSUE THREAD

**Issue by afiqff8** [jkirsons/FacialMotionCapture_v2#1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_R"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_R"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_R"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_R"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_R"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_R"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_L"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_L"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_L"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_L"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_L"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_L"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_R"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_R"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_R"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_R"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_R"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_R"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_L"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_L"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_L"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_L"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_L"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_L"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_R"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_R"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_R"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_R"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_R"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_R"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_L"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_L"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_L"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_L"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_L"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_L"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_R"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_R"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_R"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_R"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_R"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_R"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_L"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_L"].rotation_quaternion[1]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_L"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_L"].rotation_quaternion[2]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_low_4_bbone_easeout_L"].rotation_quaternion[3]
ERROR (bke.anim_sys): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\anim_sys.c:4160 BKE_animsys_eval_driver: invalid driver - pose.bones["lip_up_4_bbone_easeout_L"].rotation_quaternion[3]
loading data from : C:\Users\afiqm\Downloads\lbfmodel.yaml
Traceback (most recent call last):
  File "D:\Downloads\Vincent.blend\OpenCVAnimOperator.py ", line 30, in <module>
  File "D:\Downloads\Vincent.blend\OpenCVAnimOperator.py ", line 43, in OpenCVAnimOperator
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\core\src\persistence.cpp:719: error: (-49:Unknown error code -49) Input file is invalid in function 'cv::FileStorage::Impl::open'

**Comment by lalamax3d** [comment]
Q. what is file size of trained model on your disk??  
Q. have you managed to change model location in main operator.??

Response, i had similar error, later on i noticed, the trained model downloaded wasn't correct. it should be 56 MB or so on disk. (TIP: try downloading other repo as zip and extract model ) 
goodluck
