### ISSUE TITLE
Overload resolution failed

### ISSUE THREAD

**Issue by veyaar** [jkirsons/FacialMotionCapture_v2#4]
Please help me with this

cd "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\bin"

Traceback (most recent call last):
File "C:\Users\Admin\Downloads\Vincent (3).blend\OpenCVAnimOperator.py", line 196, in modal
cv2.error: OpenCV(4.5.2) 👎 error: (-5:Bad argument) in function 'circle'

![Screenshot 2021-05-14 173727](https://user-images.githubusercontent.com/84184382/118270426-aee5cd00-b4dd-11eb-9547-fd2658463e09.png):

Can't parse 'center'. Sequence item with index 0 has a wrong type
Can't parse 'center'. Sequence item with index 0 has a wrong type
location: :-1

**Comment by khlorghaal** [comment]
seems like [L42 fm](https://github.com/jkirsons/FacialMotionCapture_v2/blob/master/OpenCVAnimOperator.py#L42)
is in a bad state, try checking that the model is loaded properly

**Comment by barckley75** [comment]
> Please help me with this
> 
> cd "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\bin"
> 
> Traceback (most recent call last):
> File "C:\Users\Admin\Downloads\Vincent (3).blend\OpenCVAnimOperator.py", line 196, in modal
> cv2.error: OpenCV(4.5.2) 👎 error: (-5:Bad argument) in function 'circle'
> 
> ![Screenshot 2021-05-14 173727](https://user-images.githubusercontent.com/84184382/118270426-aee5cd00-b4dd-11eb-9547-fd2658463e09.png):
> 
> Can't parse 'center'. Sequence item with index 0 has a wrong type
> Can't parse 'center'. Sequence item with index 0 has a wrong type
> location: :-1

I have the same error. Did you find a solution?

**Comment by barckley75** [comment]
For sure it is not the right way to fix the problem, however this is a working away around the problem:

Change this line

`cv2.circle(image, (x, y), 2, (0, 255, 255), -1)`

with this line

`cv2.circle(image, (int(x), int(y)), 2, (0, 255, 255), -1)`

Basically, x and y are floats and for some problem that I didn't understand, floats number stops the program using cv2.circle(). Making them integer fix the problem.

**Comment by krma0n3** [comment]
thank you, worked for me

**Comment by alirezaAI** [comment]
> For sure it is not the right way to fix the problem, however this is a working away around the problem:
> 
> Change this line
> 
> `cv2.circle(image, (x, y), 2, (0, 255, 255), -1)`
> 
> with this line
> 
> `cv2.circle(image, (int(x), int(y)), 2, (0, 255, 255), -1)`
> 
> Basically, x and y are floats and for some problem that I didn't understand, floats number stops the program using cv2.circle(). Making them integer fix the problem.

thank you very much it worked for me as well! :)

**Comment by NEnhbileg** [comment]
omg thank u so much
